import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import { registerApp } from "./global";
import { setupStore } from "./store";
import "assets/css/index.css";
import "normalize.css";
const app = createApp(App);
registerApp(app);
setupStore();
app.use(store).use(router).mount("#app");
